# Generated by Django 2.1.3 on 2019-01-20 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Order', '0001_initial'),
    ]

    operations = [
    ]
