# Generated by Django 2.1.5 on 2019-01-20 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Order', '0001_initial'),
        ('User', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Users',
            new_name='User'
        ),
    ]
