# Generated by Django 2.1.5 on 2019-01-20 12:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=150, verbose_name='тип украшения')),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='название украшения')),
                ('item_decoration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.Category', verbose_name='тип украшения')),
            ],
        ),
        migrations.CreateModel(
            name='Metal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_metal', models.CharField(max_length=200, verbose_name='металл')),
            ],
        ),
        migrations.CreateModel(
            name='Stone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_stone', models.CharField(max_length=200, verbose_name='камень')),
            ],
        ),
        migrations.AddField(
            model_name='item',
            name='item_metal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.Metal', verbose_name='тип металла'),
        ),
        migrations.AddField(
            model_name='item',
            name='item_stone',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.Stone', verbose_name='тип камня'),
        ),
    ]
