# Generated by Django 2.1.3 on 2019-01-21 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20190121_1405'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='Category',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='products',
            name='metal',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='products',
            name='name',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='products',
            name='stone',
            field=models.CharField(max_length=30),
        ),
    ]
